### PR TITLE
Cvhuynh/ RepresentativesProfile

### PR DESCRIPTION
**Pull request by cvhuynh1777**
Model and Migration Update: Extended the Representative model to include fields for contact address (street, city, state, zip), political party, and photo URL. Created a migration to update the database schema accordingly.

New Profile Page: Developed views/representatives/show.html.erb as the representative's profile view. This page displays the detailed information of a representative including their contact address, political party, and photo.

Integration with Google Civic Information API: Modified the Representatives controller to fetch and store the additional information from the Google Civic Information API.

Linking to Profile Page: Updated views/representatives/search.html.haml and other relevant views where a representative's name appears to link to their new profile page.

### CODE REVIEW

**Comment by BashkirovN** [comment]
@cvhuynh1777 looks like there are some conflicts with the Master branch. Did you pull before opening the PR?

**Comment by cvhuynh1777** [comment]
> @cvhuynh1777 looks like there are some conflicts with the Master branch. Did you pull before opening the PR?

oof let me check again

**Comment by BashkirovN** [comment]
@cvhuynh1777  also make sure to write rspec tests in `spec/models/representative_spec.rb` to cover the functionality you've added

**Comment by BashkirovN** [comment]
Duplicate

**Pull request closed without merging**
